language: python
python:
  - "3.7"
services:
  - docker
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov
  - docker build -t forecastservice:latest .
  - docker images
after_success:
  - coveralls